service: myImportService
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  import:
    handler: import.handler
    timeout: 29
    memorySize: 1024
    events:
      - http:
          path: import
          method: get
          cors:
            origins: 
              - 'http://localhost'
              - 'http://localhost:3000'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowedMethods: ['GET', 'OPTIONS']
            allowCredentials: true
      - http:
          path: import
          method: options
          cors:
            origins: ['http://localhost']
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowedMethods: ['GET', 'OPTIONS']
            allowCredentials: true