service: advancePuzzle
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
          Resource:
            - arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/bazaarplanner/prod/firebase_service_account

functions:
  advancePuzzle:
    handler: advancePuzzle.handler
    timeout: 29
    memorySize: 1024
    events:
      - schedule: cron(0 0 * * ? *) # Runs at midnight UTC every day
